// react-version/src/components/Layout/Footer.jsx
import React from 'react';

const Footer = () => {
  return (
    <footer style={{ 
      borderTop: '1px solid #e5e7eb', 
      backgroundColor: 'white',
      marginTop: 'auto'
    }}>
      <div className="container">
        <div style={{ 
          padding: '2rem 0',
          textAlign: 'center',
          color: '#6b7280'
        }}>
          <p>&copy; 2024 TicketFlow. All rights reserved.</p>
          <p style={{ fontSize: '14px', marginTop: '0.5rem' }}>
            Built with React, Vue.js, and Twig
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// vue-version/src/components/Layout/Footer.vue
<template>
  <footer class="footer">
    <div class="container">
      <div class="footer-content">
        <p>&copy; 2024 TicketFlow. All rights reserved.</p>
        <p>Built with React, Vue.js, and Twig</p>
      </div>
    </div>
  </footer>
</template>

<style scoped>
.footer {
  border-top: 1px solid #e5e7eb;
  background-color: white;
  margin-top: auto;
}

.footer-content {
  padding: 2rem 0;
  text-align: center;
  color: #6b7280;
}

.footer-content p:last-child {
  font-size: 14px;
  margin-top: 0.5rem;
}
</style>
