// react-version/src/components/Layout/Header.jsx
import React from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../../contexts/AuthContext";

const Header = () => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  const handleLogout = () => {
    logout();
    navigate("/");
  };

  return (
    <header
      style={{
        borderBottom: "1px solid #e5e7eb",
        backgroundColor: "white",
        position: "sticky",
        top: 0,
        zIndex: 40,
      }}
    >
      <div className="container">
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            padding: "1rem 0",
          }}
        >
          <Link
            to="/dashboard"
            style={{
              fontSize: "1.25rem",
              fontWeight: "bold",
              color: "#3b82f6",
              textDecoration: "none",
            }}
          >
            TicketFlow
          </Link>

          <nav className="navigation">
            <Link
              to="/dashboard"
              style={{
                fontSize: "1.25rem",
                fontWeight: "bold",
                color: "#3b82f6",
                textDecoration: "none",
              }}
            >
              Multi-Framework Tickets
            </Link>
            <Link
              to="/tickets"
              style={{
                textDecoration: "none",
                color: "#374151",
                padding: "0.5rem 1rem",
              }}
            >
              Tickets
            </Link>
            <div style={{ display: "flex", alignItems: "center", gap: "1rem" }}>
              <span style={{ color: "#4b5563" }}>Welcome, {user?.name}</span>
              <button
                onClick={handleLogout}
                className="btn btn-secondary"
                style={{ fontSize: "14px" }}
              >
                Logout
              </button>
            </div>
          </nav>
        </div>
      </div>
    </header>
  );
};

export default Header;

// vue-version/src/components/Layout/Header.vue
<template>
  <header class="header">
    <div class="container">
      <div class="header-content">
        <router-link to="/dashboard" class="logo"> TicketFlow </router-link>

        <nav class="navigation">
          <router-link to="/dashboard" class="logo">
            Multi-Framework Tickets
          </router-link>
          <router-link to="/tickets">Tickets</router-link>
          <div class="user-info">
            <span>Welcome, {{ user?.name }}</span>
            <button @click="handleLogout" class="btn btn-secondary">
              Logout
            </button>
          </div>
        </nav>
      </div>
    </div>
  </header>
</template>

<script setup>
import { useRouter } from "vue-router";
import { useAuth } from "../../composables/useAuth";

const router = useRouter();
const { user, logout } = useAuth();

const handleLogout = () => {
  logout();
  router.push("/");
};
</script>

<style scoped>
.header {
  border-bottom: 1px solid #e5e7eb;
  background-color: white;
  position: sticky;
  top: 0;
  z-index: 40;
}

.header-content {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem 0;
}

.logo {
  font-size: 1.25rem;
  font-weight: bold;
  color: #3b82f6;
  text-decoration: none;
}

.navigation {
  display: flex;
  align-items: center;
  gap: 1.5rem;
}

.navigation a {
  text-decoration: none;
  color: #374151;
  padding: 0.5rem 1rem;
  border-radius: 0.5rem;
  transition: all 0.2s;
}

.navigation a:hover {
  background-color: #f3f4f6;
  color: #111827;
}

.navigation a.router-link-active {
  background-color: #3b82f6;
  color: white;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 1rem;
}

@media (max-width: 768px) {
  .navigation {
    flex-direction: column;
    gap: 0.75rem;
  }

  .header-content {
    flex-direction: column;
    gap: 1rem;
  }
}
</style>
