// vue-version/src/components/Ticket/TicketCard.vue
<template>
  <div class="card">
    <div class="ticket-header">
      <h3>{{ ticket.title }}</h3>
      <span :class="['status-badge', `status-${ticket.status}`]">
        {{ ticket.status.replace('_', ' ') }}
      </span>
    </div>
    
    <p v-if="ticket.description" class="ticket-description">
      {{ ticket.description }}
    </p>
    
    <div class="ticket-footer">
      <div class="ticket-meta">
        <div>Priority: {{ ticket.priority }}</div>
        <div>Created: {{ formatDate(ticket.createdAt) }}</div>
      </div>
      
      <div class="ticket-actions">
        <button @click="onEdit(ticket)" class="btn btn-secondary">
          Edit
        </button>
        <button @click="onDelete(ticket.id)" class="btn btn-danger">
          Delete
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
const props = defineProps({
  ticket: Object,
  onEdit: Function,
  onDelete: Function
})

const formatDate = (dateString) => {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  })
}
</script>

<style scoped>
.ticket-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 1rem;
}

.ticket-header h3 {
  margin: 0;
  flex: 1;
}

.ticket-description {
  margin-bottom: 1rem;
  color: #6b7280;
}

.ticket-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.ticket-meta {
  font-size: 14px;
  color: #9ca3af;
}

.ticket-actions {
  display: flex;
  gap: 0.5rem;
}
</style>

// react-version/src/components/Ticket/TicketCard.jsx
import React from 'react';

const TicketCard = ({ ticket, onEdit, onDelete }) => {
  const getStatusClass = (status) => {
    switch (status) {
      case 'open': return 'status-open';
      case 'in_progress': return 'status-in-progress';
      case 'closed': return 'status-closed';
      default: return '';
    }
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  return (
    <div className="card">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1rem' }}>
        <h3 style={{ margin: 0, flex: 1 }}>{ticket.title}</h3>
        <span className={`status-badge ${getStatusClass(ticket.status)}`}>
          {ticket.status.replace('_', ' ')}
        </span>
      </div>
      
      {ticket.description && (
        <p style={{ marginBottom: '1rem', color: '#6b7280' }}>
          {ticket.description}
        </p>
      )}
      
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ fontSize: '14px', color: '#9ca3af' }}>
          <div>Priority: {ticket.priority}</div>
          <div>Created: {formatDate(ticket.createdAt)}</div>
        </div>
        
        <div style={{ display: 'flex', gap: '0.5rem' }}>
          <button 
            onClick={() => onEdit(ticket)}
            className="btn btn-secondary"
            style={{ fontSize: '14px', padding: '0.5rem 1rem' }}
          >
            Edit
          </button>
          <button 
            onClick={() => onDelete(ticket.id)}
            className="btn btn-danger"
            style={{ fontSize: '14px', padding: '0.5rem 1rem' }}
          >
            Delete
          </button>
        </div>
      </div>
    </div>
  );
};

export default TicketCard;
