// react-version/src/pages/Login.jsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../contexts/ToastContext';
import { validateEmail, validatePassword } from '../utils/validation';

const Login = () => {
  const [formData, setFormData] = useState({
    email: '',
    password: ''
  });
  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  const { login } = useAuth();
  const { addToast } = useToast();
  const navigate = useNavigate();

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
    
    // Clear error when user starts typing
    if (errors[name]) {
      setErrors(prev => ({
        ...prev,
        [name]: ''
      }));
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Validate form
    const emailError = validateEmail(formData.email);
    const passwordError = validatePassword(formData.password);
    
    if (emailError || passwordError) {
      setErrors({
        email: emailError,
        password: passwordError
      });
      return;
    }
    
    setIsSubmitting(true);
    
    const result = await login(formData.email, formData.password);
    
    if (result.success) {
      addToast('Login successful!', 'success');
      navigate('/dashboard');
    } else {
      addToast(result.error, 'error');
      setErrors({ general: result.error });
    }
    
    setIsSubmitting(false);
  };

  return (
    <div style={{ 
      minHeight: '100vh', 
      display: 'flex', 
      alignItems: 'center', 
      justifyContent: 'center',
      backgroundColor: '#f8fafc',
      padding: '2rem 0'
    }}>
      <div className="card" style={{ width: '100%', maxWidth: '400px' }}>
        <h1 style={{ textAlign: 'center', marginBottom: '2rem' }}>Login</h1>
        
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label className="form-label">Email</label>
            <input
              type="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              className="form-input"
              placeholder="Enter your email"
            />
            {errors.email && <div className="form-error">{errors.email}</div>}
          </div>

          <div className="form-group">
            <label className="form-label">Password</label>
            <input
              type="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              className="form-input"
              placeholder="Enter your password"
            />
            {errors.password && <div className="form-error">{errors.password}</div>}
          </div>

          {errors.general && (
            <div className="form-error" style={{ textAlign: 'center', marginBottom: '1rem' }}>
              {errors.general}
            </div>
          )}

          <button 
            type="submit" 
            className="btn btn-primary"
            style={{ width: '100%', marginBottom: '1rem' }}
            disabled={isSubmitting}
          >
            {isSubmitting ? 'Logging in...' : 'Login'}
          </button>

          <div style={{ textAlign: 'center' }}>
            <p style={{ color: '#6b7280' }}>
              Don't have an account?{' '}
              <Link to="/auth/signup" style={{ color: '#3b82f6', textDecoration: 'none' }}>
                Sign up
              </Link>
            </p>
          </div>
        </form>

        {/* Demo credentials */}
        <div style={{ 
          marginTop: '2rem', 
          padding: '1rem', 
          backgroundColor: '#f3f4f6', 
          borderRadius: '0.5rem',
          fontSize: '14px'
        }}>
          <p style={{ margin: 0, fontWeight: '500' }}>Demo Credentials:</p>
          <p style={{ margin: '0.25rem 0 0 0' }}>Email: demo@example.com</p>
          <p style={{ margin: 0 }}>Password: password123</p>
        </div>
      </div>
    </div>
  );
};

export default Login;

// vue-version/src/views/Login.vue
<template>
  <div class="login-page">
    <div class="card login-card">
      <h1>Login</h1>
      
      <form @submit="handleSubmit">
        <div class="form-group">
          <label class="form-label">Email</label>
          <input
            type="email"
            v-model="formData.email"
            class="form-input"
            placeholder="Enter your email"
          />
          <div v-if="errors.email" class="form-error">{{ errors.email }}</div>
        </div>

        <div class="form-group">
          <label class="form-label">Password</label>
          <input
            type="password"
            v-model="formData.password"
            class="form-input"
            placeholder="Enter your password"
          />
          <div v-if="errors.password" class="form-error">{{ errors.password }}</div>
        </div>

        <div v-if="errors.general" class="form-error general-error">
          {{ errors.general }}
        </div>

        <button 
          type="submit" 
          class="btn btn-primary login-btn"
          :disabled="isSubmitting"
        >
          {{ isSubmitting ? 'Logging in...' : 'Login' }}
        </button>

        <div class="auth-link">
          <p>
            Don't have an account? 
            <router-link to="/auth/signup">Sign up</router-link>
          </p>
        </div>
      </form>

      <div class="demo-credentials">
        <p><strong>Demo Credentials:</strong></p>
        <p>Email: demo@example.com</p>
        <p>Password: password123</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { useAuth } from '../composables/useAuth'
import { useToast } from '../composables/useToast'
import { validateEmail, validatePassword } from '../utils/validation'

const router = useRouter()
const { login } = useAuth()
const { addToast } = useToast()

const formData = reactive({
  email: '',
  password: ''
})

const errors = ref({})
const isSubmitting = ref(false)

const handleSubmit = async (e) => {
  e.preventDefault()
  
  const emailError = validateEmail(formData.email)
  const passwordError = validatePassword(formData.password)
  
  if (emailError || passwordError) {
    errors.value = {
      email: emailError,
      password: passwordError
    }
    return
  }
  
  isSubmitting.value = true
  
  const result = await login(formData.email, formData.password)
  
  if (result.success) {
    addToast('Login successful!', 'success')
    router.push('/dashboard')
  } else {
    addToast(result.error, 'error')
    errors.value.general = result.error
  }
  
  isSubmitting.value = false
}
</script>

<style scoped>
.login-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #f8fafc;
  padding: 2rem 0;
}

.login-card {
  width: 100%;
  max-width: 400px;
}

.login-btn {
  width: 100%;
  margin-bottom: 1rem;
}

.auth-link {
  text-align: center;
}

.auth-link p {
  color: #6b7280;
}

.auth-link a {
  color: #3b82f6;
  text-decoration: none;
}

.demo-credentials {
  margin-top: 2rem;
  padding: 1rem;
  background-color: #f3f4f6;
  border-radius: 0.5rem;
  font-size: 14px;
}

.general-error {
  text-align: center;
  margin-bottom: 1rem;
}
</style>
